### PR TITLE
Fix segfault possibilities

### LINKED ISSUE #27: Add sasl and enif mutexes
Per the cyrus-sasl documentation, in order to have some assurance of thread safety, sasl mutex callbacks must be provided. In addition, we should also wrap sasl calls in an enif mutex to be on the safe side.

### PR DESCRIPTION
**Pull request by starbelly**
Resolves #27 

This PR addresses potential segfault possibilities. Recently, I encountered a segfault in production. Reproducing this is extremely difficult (non-deterministic), such that I took a proverbial sledge hammer to the code to eliminate any potential segfault possibility. The changes within this commit resulted in no more segmentation faults. 

The behavior just up to a segfault through debug logging showed that at some point memory _seemed_ to be corrupted, such that a pointer for the principal winded up pointing to garbage. Specifically, the principal value (pointer) placed into a callback structure which resides in the sasl context is fetched by a callback we provide, eventually the callback returns a garbage value. cyrus-sasl attempts to validate the value, and believes it to be an all white space username (the value is usually a few bytes, and contains no `@` char) [here](https://github.com/cyrusimap/cyrus-sasl/blob/7a6b45b177070198fed0682bea5fa87c18abb084/lib/canonusr.c#L355), when this happens the value that's depended on [here](https://github.com/cyrusimap/cyrus-sasl/blob/7a6b45b177070198fed0682bea5fa87c18abb084/plugins/gssapi.c#L2063) is not set and invalid memory access occurs. This is the rough summary, but I can potentially expand on this more. 

The conditions for the segfault are thus : 

1. Linux with cyrus-sasl version 2.1.27 to 2.1.28 
1. Erlang/OTP 25 - 26 
1. The usage of super carrier with a large amount of memory in play (40GB to 500GB) 
1. Continuously starting and stopping of brod client(s) (i.e., every few minutes or less)
1.  A fair number of active processes in erts (tens of thousands at least). 

In sum : 

1. Do not share binary argument pointers with cyrus-sasl 
1. Do not allow multiple processes to share a context via a controlling process lock check 
1. Use sasl_mutex callbacks recommended per cyrus-sasl 
1. Wrap all calls to cyrus-sasl with mutexes to guard against global state utilization internally in cyrus-sasl 

The mutexes at this point are the most dubious per the addition of a lock to prevent multiple processes from sharing a context. However, it still may be prudent.

### CODE REVIEW

File: c_src/sasl_auth.c [hunk 1]
```diff
@@ -134,24 +238,56 @@ static ERL_NIF_TERM sasl_cli_new(ErlNifEnv* env, int UNUSED(argc), const ERL_NIF
 
     state->mech_set = 0;
 
+    enif_self(env, &state->controlling_process);
+
+    state->controller_lock = enif_mutex_create("sasl_auth.controller_lock");
+
+    state->principal = copy_bin(principal);
```
Comment (starbelly) [inline c_src/sasl_auth.c:245]: This fixes a thing we should have never been doing and could result in memory corruption (treating the argument as non-transient).

File: c_src/sasl_auth.c [hunk 2]
```diff
@@ -32,17 +33,86 @@ ERL_NIF_TERM ATOM_UNKNOWN;
 typedef struct {
     sasl_conn_t* conn;
     sasl_callback_t callbacks[16];
+    unsigned char* principal;
```
Comment (starbelly) [inline c_src/sasl_auth.c:36]: We ensure our copies will be held on to throughout the duration of the context by placing them into our structure

File: c_src/sasl_auth.c [hunk 3]
```diff
@@ -114,6 +201,23 @@ static int sasl_cyrus_cb_getsimple(void* context, int id, const char** result, u
     return *result ? SASL_OK : SASL_FAIL;
 }
 
+static int sasl_auth_process_check(ErlNifEnv* env, sasl_state_t* state)
```
Comment (starbelly) [inline c_src/sasl_auth.c:204]: In reviewing the code, I simply thought to myself, without a check like this in place, the library is unsafe. That is to say, if a user of this library (devoid of brod) is not aware of thread safety issues, it will blow up in their face. This was added in after thread mutexes were placed in, it may be per this change it obviates the need for thread mutexes .

File: c_src/sasl_auth.c [hunk 4]
```diff
@@ -237,9 +396,43 @@ static ERL_NIF_TERM sasl_cli_step(ErlNifEnv* env, int UNUSED(argc), const ERL_NI
...
     } else {
+
         ret = ERROR_TUPLE(
             env, enif_make_tuple2(env, enif_make_int(env, -4), str_to_bin(env, "No MECH set", 12)));
     }
+    enif_free(challenge_in);
+    return ret;
+}
+
+static ERL_NIF_TERM sasl_cli_done(ErlNifEnv* env, int UNUSED(argc), const ERL_NIF_TERM argv[])
```
Comment (starbelly) [inline c_src/sasl_auth.c:407]: This was added as we should not depend on the garbage collector to run to destroy the context, rather the destruction of the context, etc should be explicit, and the dtor callback becomes a last ditch effort.  This will require a a small patch to brod_gssapi.

File: c_src/sasl_auth.c [hunk 5]
```diff
@@ -271,17 +466,26 @@ static ERL_NIF_TERM sasl_kinit(ErlNifEnv* env, int UNUSED(argc), const ERL_NIF_T
             || !enif_inspect_binary(env, argv[1], &principal_in)))
         return enif_make_badarg(env);
 
+    principal_mut = copy_bin(principal_in);
```
Comment (starbelly) [inline c_src/sasl_auth.c:469]: Similar to not utilizing transient arguments with cyrus-sasl functions, we simply do the same here, although this may seem like overkill, we definitely do not want to the functions to have a chance to mutate what we pass in. In a nutshell, it's a safety measure.

File: c_src/sasl_auth.c [hunk 6]
```diff
@@ -212,19 +359,31 @@ static ERL_NIF_TERM sasl_cli_step(ErlNifEnv* env, int UNUSED(argc), const ERL_NI
...
     const char* out;
     unsigned int outlen;
+    unsigned char* challenge_in = NULL;
     ERL_NIF_TERM ret;
 
     sasl_interact_t* interact = NULL;
 
-    if (state->mech_set) {
+    if (state->mech_set && state->conn) {
+        challenge_in = copy_bin(challenge);
```
Comment (starbelly) [inline c_src/sasl_auth.c:375]: In this particular instance the debug emulator would abort warning that indeed cyrus-sasl seemed to mutate the challange, thus we avoid that possibility all together.

File: c_src/sasl_auth.c [hunk 7]
```diff
@@ -32,17 +33,86 @@ ERL_NIF_TERM ATOM_UNKNOWN;
...
+            enif_free(state->service);
+        }
+
+        if (state->host != NULL) {
+            enif_free(state->host);
+        }
+    }
+}
+
+static void* sasl_mutex_alloc(void) { return enif_mutex_create("sasl_auth.callback"); }
```
Comment (starbelly) [inline c_src/sasl_auth.c:80]: The usage of mutexes here is simply per cyrus-sasl's own documentation which states (paraphrasing) "This library is **believed** to be thread safe if sasl mutexes are provided."

As stated elsewhere, the useage of mutexes _should_ be obviated by the usage of a single controller lock to protect the user of the library.

File: c_src/sasl_auth.c [hunk 8]
```diff
@@ -166,12 +302,17 @@ static ERL_NIF_TERM sasl_list_mech(ErlNifEnv* env, int UNUSED(argc), const ERL_N
 
     if ((!enif_get_resource(env, argv[0], sasl_resource, (void**)&state))) {
         return enif_make_badarg(env);
+    } else if (!sasl_auth_process_check(env, state)) {
+        return enif_raise_exception(env, ATOM_NOT_CONTROLLING_PROCESS);
     }
 
+    enif_mutex_lock(state->controller_lock);
```
Comment (starbelly) [inline c_src/sasl_auth.c:309]: The additional usage of the controller lock may not be needed anymore, simply per the check of the controlling process in conjunction with not exposing a method for changing the controlling process. However, I had concern over the use of global state in cyrus-sasl.

**Comment by starbelly** [comment]
Ping @kjellwinblad

File: c_src/sasl_auth.c (hunk 4 above)
Comment (kjellwinblad) [reply c_src/sasl_auth.c:407]: I wonder why we cannot rely on the garbage collector to destroy the context? Is there any reason that it need to be freed as fast as possible? Any name conflict?

**Review by kjellwinblad — APPROVED** [review]
Sorry for the slow response. Looks good to me (I'm not an expert of this code but I went through all the changes and the comments and could not spot something that seems incorrect). Have you tested this change in any system and if so, did it solve any crashes/bugs you experienced before the changes?

File: c_src/sasl_auth.c (hunk 4 above)
Comment (starbelly) [reply c_src/sasl_auth.c:407]: brod _should_be fine devoid of this change per the design (i.e., the context is tied to a process that can be destroyed), still, we'd be relying on time (i.e., it's not a question of `if` but a question of `when`). 

Someone who might come along and use this library (sasl_auth) however, might know now that's the way to use it, as such, at the very least many connections could be accumulated, at worst a segfault may ensue per sharing the context between processes.

**Comment by starbelly** [comment]
> Sorry for the slow response. Looks good to me (I'm not an expert of this code but I went through all the changes and the comments and could not spot something that seems incorrect). Have you tested this change in any system and if so, did it solve any crashes/bugs you experienced before the changes?

No worries on the slow response, slow is good 😄 

Yes, after these changes, all segfaults in systems we utilize brod in ceased, and has been months now. I still wanted to come back to this and narrow it down and use scalpel vs a sledge hammer to drive the changes here, but I think the sledgehammer approach here doesn't hurt anything, especially since on my end anyway, there's a lack of trust as far as the library being utilized goes (libsasl).

File: c_src/sasl_auth.c (hunk 4 above)
Comment (kjellwinblad) [reply c_src/sasl_auth.c:407]: I think sharing the context between processes should be fine as I think it is reference counted but I don't think it hurts with a way to explicitly destroy the context.

Comment (starbelly) [reply c_src/sasl_auth.c:407]: Yes, it should be fine, but I found in testing that sharing a sasl context between processes can lead to a segmentation fault (use-after-free). It might be that with all the other changes I introduced here, that's not an issue, especially with the highly defensive approach of making sure the process passing in the context is also the owner. Never the less, I did not feel good about it. 

n.b., there's an old thread where Sverker talks about why you shouldn't rely on gc for resource reclamation : http://erlang.org/pipermail/erlang-questions/2020-November/100131.html

I realized now I might have merged this a little too quickly, let's keep this discussion going though if so, and if we need to make some more changes. Especially if may lead to documentation improvements in OTP around nif resources 😄

Comment (starbelly) [reply c_src/sasl_auth.c:407]: Additionally, I remember this being talked about here : https://erlangforums.com/t/use-cases-for-port-drivers-when-is-it-better-to-use-a-port-driver-instead-of-a-nif/1772/4
